name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{ github.run_id }} --build-arg BUILD_CONFIGURATION=Release

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push image to Docker Hub
      run: docker push dockingincsharp/portfolio

    - name: Deploy to Heroku
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/my-image-name:${{ github.run_id }} registry.heroku.com/my-app/web
        echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com
        docker push registry.heroku.com/my-app/web
        heroku container:release web --app my-app
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
